### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by marc3k18** [tronikos/gassist_text#1]
Hello!

It's more a question than an issue.

For the playback option (play music in the kitchen) it's a limitation of the API, or it's something that will be fixed in the future?

Thanks!

**Comment by tronikos** [comment]
Yes it's a limitation of the API. Nothing I can do about it.
See https://github.com/googlesamples/assistant-sdk-python/issues/65
where it says "The library now supports news & podcasts."
Only those currently work. (rain sounds and white noise for whatever reason fall in the news and are working)

**Comment by slyoldfox** [comment]
@tronikos maybe some more thing can be made possible using https://home.google.com 

Once you create some yaml automations, it seems that most commands go to https://googlehomefoyer-pa.clients6.google.com/$rpc/google.internal.home.foyer.v1.AutomationService/

Including:

- https://googlehomefoyer-pa.clients6.google.com/$rpc/google.internal.home.foyer.v1.AutomationService/ListAutomations
- https://googlehomefoyer-pa.clients6.google.com/$rpc/google.internal.home.foyer.v1.AutomationService/GetAutomation
- https://googlehomefoyer-pa.clients6.google.com/$rpc/google.internal.home.foyer.v1.AutomationService/ExecuteAutomation

Of course we would need  to figure out which IDs are being sent as cookie values ... let's hope this API becomes public at some point ..
