### ISSUE TITLE
Some "turn on/off's" work, others dont

### ISSUE THREAD

**Issue by Tuttle13** [tronikos/gassist_text#2]
Thanks for this integration - it helps avoid having to go down the path of converting over things like my SmartLife power plugs to Tuya (there's no Smart life integration). But an issue I've found is that while one plug can be triggered (ie "turn on gym tv" which is it's name in Google Home), another identical plug doesn't respond to "turn on gym power" (but it toggles when in Google Home). I have tired renaming it, but no change in outcome. 
Ideally the solution would be the ability to trigger routine phrases. Another request is, like the main page in Google Home, the ability to "toggle" a on/off device, rather than specially on or off (allowing got single press buttons to trigger that device on and off). Obviously it can be solved via an _else_ automation, but a toggle would be easier if possible.

**Comment by tronikos** [comment]
Unfortunately nothing I can do about it. I updated the README to not report such issues here. Instead report them directly to Google.
